version: '3.9'

services:
  mysql-master:
    image: 'bitnami/mysql:latest'
    container_name: mysql-master
    ports:
      - '3306:3306'
    volumes:
      - mysql_master_data:/bitnami/mysql/data
    environment:
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_ROOT_PASSWORD=master_root_password
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
      - MYSQL_DATABASE=my_database
    networks:
      - mysql_network

  mysql-slave:
    image: 'bitnami/mysql:latest'
    container_name: mysql-slave
    ports:
      - '3307:3306'
    depends_on:
      - mysql-master
    volumes:
      - mysql_slave_data:/bitnami/mysql/data
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_MASTER_HOST=mysql-master
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_MASTER_ROOT_PASSWORD=master_root_password
    networks:
      - mysql_network

volumes:
  mysql_master_data:
    driver: local
  mysql_slave_data:
    driver: local

networks:
  mysql_network:
    driver: bridge
